#!/usr/bin/env sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
BRANCH=${1:-$CURRENT_BRANCH}
RANDOM_BRANCH_NAME=$(cat /dev/urandom | tr -dc '_A-Za-z0-9' | head -c ${1:-32})

git checkout -b $RANDOM_BRANCH_NAME
git branch -D $BRANCH
git fetch --all
git checkout $BRANCH
git branch -D $RANDOM_BRANCH_NAME
