#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

CONFIG_FILE = File.expand_path('~/.config/.projections.json')

unless File.exist?(CONFIG_FILE)
  puts "Config '#{CONFIG_FILE}' not found!"
  exit
end

if Dir.exist?('./apps')
  (Dir.entries('./apps') - %w[. ..]).each { |dir| FileUtils.cp(CONFIG_FILE, "./apps/#{dir}") }
elsif Dir.exist?('./lib')
  FileUtils.cp(CONFIG_FILE, './')
end
