#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

# Usage:
#   ruby2json <file>
#   cat <file> | ruby2json
#   echo <string> | ruby2json
#   ruby2json (press Ctrl+D to finish input)

content = ARGF.read
hash = eval(content)
print JSON.pretty_generate(hash)
