#!/usr/bin/env ruby

require 'json'

# Usage:
#   ruby2json <file>
#   cat <file> | ruby2json
#   echo <string> | ruby2json
#   ruby2json (enter Ctrl+D to exit)

content = ARGF.read
hash = eval(content)
print JSON.pretty_generate(hash)
