#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'yaml'

DEFAULT_OPTIONS = {
  config: File.expand_path('~/.config/starter.yml')
}.freeze
CURRENT_DIR = Dir.pwd

def options_parser(options)
  OptionParser.new('Usage: start') do |option|
    option.on('-c', '--config FILE', "config file. Default: #{DEFAULT_OPTIONS[:config]}") do |value|
      options[:config] = File.expand_path(value)
    end
    option.on_tail('--help', 'display a usage message') do
      puts option
      exit
    end
  end
end

def parse_options!(args = ARGV)
  DEFAULT_OPTIONS.dup.tap do |options|
    options_parser(options).parse!(args)

    config = options.fetch(:config)
    raise "Config '#{config}' not found" unless File.exist?(config)
  end
end

def target_dir?(path)
  File.expand_path(path) == CURRENT_DIR
end

def compose_command(command)
  case command
  when String then command
  when Array then command.join(' && ')
  end
end

YAML.load_file(parse_options![:config]).each do |path, command|
  next unless target_dir?(path)

  compose_command(command).tap do |composed_command|
    puts composed_command
    exec composed_command
  end
end
