#!/usr/bin/env sh

DEFAULT_SHELL_CONFIG="$HOME/.bashrc"
SHELL_CONFIG=${SHELL_CONFIG:-$DEFAULT_SHELL_CONFIG}

for path in $@; do
  echo "$path" |
  sed "s|~|$HOME|" |
  sed "s|$HOME|\$PATH:\$HOME|" |
  xargs -I {} echo "export PATH=\"{}\"" >> $SHELL_CONFIG
done
