#!/usr/bin/env sh

USAGE="Usage: add_path path/to/bin/dir..."

CURRENT_SHELL=$(basename $SHELL)

[ -z "$1" ] && echo $USAGE && exit

if [ -z "$SHELL_CONFIG" ]; then
  case $CURRENT_SHELL in
    zsh)
      SHELL_CONFIG="$HOME/.zshrc"
    ;;
    bash)
      SHELL_CONFIG="$HOME/.bashrc"
    ;;
    *)
      echo "'$CURRENT_SHELL' is not supported"
      exit
    ;;
  esac
fi

[ ! -f "$SHELL_CONFIG" ] && touch $SHELL_CONFIG

for path in $@; do
  echo "$path" |
  sed "s|~|$HOME|" |
  sed "s|$HOME|\$PATH:\$HOME|" |
  xargs -I {} echo "export PATH=\"{}\"" >> $SHELL_CONFIG
done
