#!/usr/bin/env ruby
# frozen_string_literal: true

ALIASES_FILE = File.expand_path(ENV.fetch('ALIASES_FILE', '~/.bashrc'))

COMMANDS = {
  add: 'add',
  delete: 'del',
  change: 'chg'
}.freeze

USAGE_MESSAGE = <<~USAGE
  Usage: als add name value
         als del name
USAGE

def add_alias(name)
  value = ARGV[2..-1].join(' ')
  File.open(ALIASES_FILE, 'a') { |file| file.puts "alias #{name}='#{value}'" }
end

def delete_alias(name)
  lines = File.readlines(ALIASES_FILE).reject { |line| line.start_with?("alias #{name}=") }
  File.open(ALIASES_FILE, 'w') { |file| file.write(lines.join) }
end

command, name = ARGV

case command
when COMMANDS[:add]
  add_alias(name)
when COMMANDS[:delete]
  delete_alias(name)
when COMMANDS[:change]
  delete_alias(name)
  add_alias(name)
else
  puts USAGE_MESSAGE
end
